name: Documentation Deployment

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'
          cache: maven

      - name: Build Javadoc
        run: mvn -B -DskipTests javadoc:javadoc

      - name: Debug Javadoc output
        run: |
          echo "==== Listing target/site ===="
          ls -R target/site || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs
